export { Login as ScreenLogin } from "./Login"
export { Cadastrar as ScreenCadastrar } from "./Cadastrar"
export { Mapa as ScreenMapa } from "./Mapa"
export { SuasDenuncias as ScreenSuasDenuncias } from "./SuasDenuncias"
export { CadastroDenuncias as ScreenCadastroDenuncias  } from "./CadastroDenuncias"
export { ScreenCamera as ScreenCamera } from "./Camera"
